version: 1

# Vibe Scale configuration for the Vibe Scale repo itself
# The analyzer file contains pattern strings that would trigger false positives

files:
  ignore:
    # Ignore test files
    - "tests/**"
    - "**/*.test.ts"
    - "**/*.spec.ts"
    # Ignore the analysis module - it contains detection patterns as strings
    - "src/analysis/**"
    # Ignore config examples in docs
    - "**/*.md"

rules:
  # Console debugging is intentional in this codebase for logging
  CONSOLE_DEBUG:
    enabled: false

# Enable GitHub issue creation for high-severity findings
reporting:
  create_issues: true
  max_issues_per_pr: 3
  issue_severity_threshold: "high"
  issue_labels: ["vibe-scale", "production-risk"]
