name: 'Vibe Scan'
description: 'Analyze pull requests for vibe-coded production risks'
author: 'Vibe Scan'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  groq-api-key:
    description: 'Groq API key for LLM analysis (optional but recommended)'
    required: false
  confidence-threshold:
    description: 'Minimum confidence score to display findings (0.0-1.0)'
    required: false
    default: '0.6'
  fail-on-high:
    description: 'Fail the action if high-severity findings are detected'
    required: false
    default: 'false'
  validate-findings:
    description: 'Use LLM to validate findings and filter false positives'
    required: false
    default: 'true'

outputs:
  vibe-score:
    description: 'The computed vibe score (0-100)'
  findings-count:
    description: 'Total number of findings'
  high-count:
    description: 'Number of high-severity findings'
  filtered-count:
    description: 'Number of findings filtered as false positives'

runs:
  using: 'node20'
  main: 'dist/action/index.js'
